databasemainserver:
  hosts:
    mainserver:
      ansible_connection: ssh
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_ssh_private_key_file: .vagrant/machines/webserver1/vmware_fusion/private_key
      ansible_user: vagrant
databasereplicaservers:
  hosts:
    replica1:
      ansible_connection: ssh
      ansible_host: 192.168.181.129
      ansible_port: 22
      ansible_ssh_private_key_file: .vagrant/machines/webserver2/vmware_fusion/private_key
      ansible_user: vagrant
redisservers:
  hosts:
    redisserver1:
      ansible_connection: ssh
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_ssh_private_key_file: .vagrant/machines/webserver1/vmware_fusion/private_key
      ansible_user: vagrant
webservers:
  hosts:
    webserver1:
      ansible_connection: ssh
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_ssh_private_key_file: .vagrant/machines/webserver1/vmware_fusion/private_key
      ansible_user: vagrant
