---
webservers:
  hosts:
    webserver1:
      ansible_host: 192.168.181.128
      ansible_port: 22
      ansible_connection: ssh
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/vm1/vmware_fusion/private_key

postgresmainserver:
  hosts:
    mainserver:
      ansible_host: 192.168.181.128
      ansible_port: 22
      ansible_connection: ssh
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/vm1/vmware_fusion/private_key

postgresreplicaservers:
  hosts:
    replica1:
      ansible_host: 192.168.181.129
      ansible_port: 22
      ansible_connection: ssh
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/vm2/vmware_fusion/private_key

redisservers:
  hosts:
    redisserver1:
      ansible_host: 192.168.181.128
      ansible_port: 22
      ansible_connection: ssh
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/vm1/vmware_fusion/private_key

pythonwebservers:
  hosts:
    server1:
      ansible_host: 192.168.181.128
      ansible_port: 22
      ansible_connection: ssh
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/vm1/vmware_fusion/private_key
