---
- name: Setup Golang
  vars_files:
    - group_vars/golangwebservers.yml
  hosts: webservers
  become: true
  vars:
    architecture_mapping:
      aarch64: arm64
      amd: amd64
      # Add more mappings as needed
  tasks:
    - name: "Download go tar file"
      get_url:
        url: https://go.dev/dl/go{{golang_version}}.linux-{{architecture_mapping[ansible_architecture] | default(ansible_architecture)}}.tar.gz
        dest: "/tmp/go{{golang_version}}.linux-{{architecture_mapping[ansible_architecture] | default(ansible_architecture)}}.tar.gz"
        mode: '0755'

    - name: "Extract go tar file"
      unarchive:
        src: "/tmp/go{{golang_version}}.linux-{{architecture_mapping[ansible_architecture] | default(ansible_architecture)}}.tar.gz"
        dest: /usr/local
        remote_src: yes

    - name: "Delete go tar file"
      file:
        path: "/tmp/go{{golang_version}}.linux-{{architecture_mapping[ansible_architecture] | default(ansible_architecture)}}.tar.gz"
        state: absent

    - name: "Set go path"
      become: false
      lineinfile:
        path: /home/{{ ansible_user }}/.profile
        line: 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin'
        create: true
        state: present

    - name: "Reload profile"
      become: false
      shell: . /home/{{ ansible_user }}/.profile && go version
      args:
        executable: /bin/bash
        